---
info:
  title: Rubyntlm
  description: Ruby implementation of MSFT's NTLM
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/rubyntlm
  x-cortex-tag: rubyntlm
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
